# Generated by Django 5.2.2 on 2025-06-08 20:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='entity.entity')),
            ],
        ),
        migrations.CreateModel(
            name='InTouchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('request_payload', models.JSONField()),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SENT', 'Envoyée'), ('RECEIVED', 'Callback reçu'), ('SUCCESS', 'Succès confirmé'), ('FAILED', 'Échec confirmé')], default='SENT', max_length=20)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intouch_log', to='transaction.transaction')),
            ],
            options={
                'verbose_name': 'Trace des appels InTouch',
                'verbose_name_plural': 'Traces des appels InTouch',
                'ordering': ['-sent_at'],
            },
        ),
    ]
