# Generated by Django 5.2.7 on 2025-11-04 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0002_alter_appuser_options_alter_appuser_email_and_more"),
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Montant"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créée le"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="details",
            field=models.JSONField(blank=True, null=True, verbose_name="Détails"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="entity.entity",
                verbose_name="Entité",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="purpose",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Objet"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Référence"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("SUCCESS", "Réussie"),
                    ("FAILED", "Échouée"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modifiée le"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Identifiant",
            ),
        ),
        migrations.CreateModel(
            name="PaymentProviderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Envoyé le"),
                ),
                (
                    "callback_received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Callback reçu le"
                    ),
                ),
                ("request_payload", models.JSONField(verbose_name="Requête envoyée")),
                (
                    "response_payload",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Réponse reçue"
                    ),
                ),
                (
                    "http_status",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Code HTTP"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Envoyée"),
                            ("RECEIVED", "Callback reçu"),
                            ("SUCCESS", "Succès confirmé"),
                            ("FAILED", "Échec confirmé"),
                        ],
                        default="SENT",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="MPP",
                        help_text="Nom du provider (MPP, InTouch, etc.)",
                        max_length=50,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_log",
                        to="transaction.transaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'appel provider",
                "verbose_name_plural": "Journaux d'appels provider",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.DeleteModel(
            name="InTouchLog",
        ),
    ]
