# Generated by Django 5.1.7 on 2025-06-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="purpose",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
