# Generated by Django 5.1.7 on 2025-06-05 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0002_transaction_purpose"),
    ]

    operations = [
        migrations.CreateModel(
            name="InTouchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("callback_received_at", models.DateTimeField(blank=True, null=True)),
                ("request_payload", models.JSONField()),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("http_status", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Envoyée"),
                            ("RECEIVED", "Callback reçu"),
                            ("SUCCESS", "Succès confirmé"),
                            ("FAILED", "Échec confirmé"),
                        ],
                        default="SENT",
                        max_length=20,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intouch_log",
                        to="transaction.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trace des appels InTouch",
                "verbose_name_plural": "Traces des appels InTouch",
                "ordering": ["-sent_at"],
            },
        ),
    ]
