# Generated by Django 5.1.7 on 2025-06-08 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_alter_entity_options_alter_entity_managers_and_more'),
        ('transaction', '0003_intouchlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='entity.entity'),
        ),
    ]
