# Generated by Django 5.2.7 on 2025-11-04 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appuser",
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AlterField(
            model_name="appuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="entity.entity",
                verbose_name="Partenaire",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Pays"
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="entity_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Identifiant",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("MERCHANT", "Marchand"),
                    ("CLIENT", "Client API"),
                    ("INTERNAL", "Système interne"),
                ],
                default="CLIENT",
                max_length=10,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Téléphone",
            ),
        ),
    ]
